'fact'
'fact'
KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'
KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'
KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'
KeyError at line 48 of /home/runner/teny/cogs/fact.py: 'fact'
